language: node_js
node_js:
- '10'
- '12'
- node
jobs:
  include:
  - stage: style
    script: yarn style:check
  - stage: lint
    script: yarn lint
deploy:
  provider: npm
  email: mazinsw@gmail.com
  api_key:
    secure: wHpLVwvXMeT8O4lXfuA10lO9zW+YZLnjCXse25EDczicTmp0CCzBzZK8GI4mWfaosNftrokKBchHl5i6U86q9AXPf5H6p/2j1wUna5UFaDXA8E1dTflPlsRiBGkQRld8HpvE8Ifd3coJySKIyvGh3BIwTU4g/BYtYMGEY6hLTpSLVtmiH1omNvuSMYSp3EhtgSVfvL1WaEneu4nFcJRVY8BEnVnJme/oCU/a/zvvPZJS2iyLnU59y0uemDKiiWjJP84kqp4PbZOj9NF3hgwNl7Ud/wyh7zr8Sfor9fILk2gxEh+gscCvOoZSbZmT6Ii3IOEOm110TOYEhYZiRFR2Z723/0o79TtYlkMf931kiN0D7+xeKnJw+LntKygaCMhG9ssQ86Ogrl2FnYe22aep19M/vjk2XhveAiCDuhRb3h5Mh18NLhajx0jjAs/YzMflqrA5Wk7vTQTgbrNSbTEue7Pj8a94nFX9RauuA5jfnCttIA3phG6aiOmlhj1JFlIMpnT2QvDizxkV2mz8HA+j6KXl0klQ+E2Lxvxu9UrduF+RoSsvla7IvyZrLvkfL84x9CNXs61E3gQx5dtZ6jzYcemQWPYVeHVUJtdvgeyk8D6E46IeTwuVTbhWUejBwx1sRgQSAem6tyCIrmNmt0HrSVnZySlJ2D/gNS6xtRjvMLQ=
  on:
    tags: true
    repo: grandchef/escpos-buffer
